
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RestauracjaWebServiceImplService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8080/Restauracja/RestauracjaWebService?wsdl")
public class RestauracjaWebServiceImplService
    extends Service
{

    private final static URL RESTAURACJAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESTAURACJAWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RESTAURACJAWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice/", "RestauracjaWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Restauracja/RestauracjaWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESTAURACJAWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RESTAURACJAWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RestauracjaWebServiceImplService() {
        super(__getWsdlLocation(), RESTAURACJAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RestauracjaWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESTAURACJAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RestauracjaWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESTAURACJAWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RestauracjaWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESTAURACJAWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RestauracjaWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RestauracjaWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RestauracjaWebService
     */
    @WebEndpoint(name = "RestauracjaWebServiceImplPort")
    public RestauracjaWebService getRestauracjaWebServiceImplPort() {
        return super.getPort(new QName("http://webservice/", "RestauracjaWebServiceImplPort"), RestauracjaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RestauracjaWebService
     */
    @WebEndpoint(name = "RestauracjaWebServiceImplPort")
    public RestauracjaWebService getRestauracjaWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "RestauracjaWebServiceImplPort"), RestauracjaWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESTAURACJAWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RESTAURACJAWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RESTAURACJAWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
